"""
Module for evaluating FastAPI code generation quality and correctness.
"""

import ast
import re
import logging
from typing import Dict, Any, NamedTuple

import torch


def extract_code_from_markdown(text: str) -> str:
    """
    Extract code blocks from markdown formatted text.
    
    Args:
        text: Input text that may contain markdown code blocks
        
    Returns:
        str: Extracted code
    """
    # Try to extract code blocks
    code_block_pattern = r'```(?:python|py)?\n?(.*?)```'
    matches = re.findall(code_block_pattern, text, re.DOTALL)
    
    if matches:
        return '\n'.join(matches).strip()
    
    # If no code blocks, return the text as-is
    return text.strip()


class EvaluationResult(NamedTuple):
    """
    Result of FastAPI code evaluation.
    """
    score: float
    is_valid_python: bool
    has_imports: bool
    has_endpoint: bool
    has_error_handling: bool
    has_type_hints: bool
    syntax_errors: list
    missing_elements: list


def prepare_model_for_inference(model):
    """
    Prepare a fine-tuned model for inference by disabling training-specific settings.
    
    Args:
        model: The fine-tuned model
        
    Returns:
        model: Model prepared for inference
    """
    # Set model to evaluation mode
    model.eval()
    
    # Disable gradient checkpointing for inference
    if hasattr(model, 'gradient_checkpointing_disable'):
        model.gradient_checkpointing_disable()
    
    # For PEFT models, disable gradient checkpointing on the base model too
    if hasattr(model, 'base_model') and hasattr(model.base_model, 'gradient_checkpointing_disable'):
        model.base_model.gradient_checkpointing_disable()
        
    return model


def generate_response(model, tokenizer, prompt, max_new_tokens=512) -> str:
    """
    Generate response from the model with proper inference setup.

    Args:
        model: The fine-tuned model
        tokenizer: The tokenizer
        prompt: Input prompt
        max_new_tokens: Maximum new tokens to generate
    
    Returns:
        str: Response generated by the Language Model
    """
    # Prepare model for inference
    model = prepare_model_for_inference(model)
    
    # Format prompt for CodeLlama
    formatted_prompt = f"[INST] {prompt} [/INST]"
    inputs = tokenizer(formatted_prompt, return_tensors="pt", padding=True)

    if torch.cuda.is_available():
        inputs = {k: v.cuda() for k, v in inputs.items()}
        
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=0.1,
            do_sample=True,
            pad_token_id=tokenizer.pad_token_id,
            use_cache=True,  # Enable KV caching for efficiency
            num_return_sequences=1,
        )
    
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return response[len(formatted_prompt):].strip()


class FastAPIEvaluator:
    """
    Evaluates FastAPI code generation responses.
    """
    
    def __init__(self):
        self.logger = logging.getLogger(__name__)
    
    def evaluate_response(self, prompt: str, response: str) -> EvaluationResult:
        """
        Evaluates a single response for FastAPI code quality.
        
        Args:
            prompt: The original prompt
            response: The generated code response
            
        Returns:
            EvaluationResult: Evaluation results
        """
        code = extract_code_from_markdown(response)
        
        # Check if valid Python
        syntax_errors = []
        is_valid_python = True
        try:
            ast.parse(code)
        except SyntaxError as e:
            syntax_errors.append(str(e))
            is_valid_python = False

        # Check for FastAPI imports
        has_imports = bool(re.search(r"from\s+fastapi\s+import|import\s+fastapi", code, re.IGNORECASE))
        
        # Check for endpoints
        endpoint_pattern = r"@\s*(app|router)\.(get|post|put|delete|patch)\s*\("
        has_endpoint = bool(re.search(endpoint_pattern, code, re.IGNORECASE))
        
        # Check for error handling
        error_patterns = [
            r"HTTPException",
            r"try\s*:",
            r"raise\s+\w+",
            r"status\.HTTP_[45]\d\d",
        ]
        has_error_handling = any(bool(re.search(pattern, code, re.IGNORECASE)) for pattern in error_patterns)
        
        # Check for type hints
        type_hint_pattern = r"def\s+\w+\s*\([^)]*:\s*\w+"
        has_type_hints = bool(re.search(type_hint_pattern, code))
        
        # Missing elements
        missing_elements = []
        if not has_imports:
            missing_elements.append("FastAPI imports")
        if not has_endpoint:
            missing_elements.append("API endpoints")
        if not has_error_handling:
            missing_elements.append("Error handling")
        if not has_type_hints:
            missing_elements.append("Type hints")
        
        # Calculate score
        score = 0.0
        if is_valid_python:
            score += 0.3
        if has_imports:
            score += 0.2
        if has_endpoint:
            score += 0.3
        if has_error_handling:
            score += 0.1
        if has_type_hints:
            score += 0.1
        
        return EvaluationResult(
            score=score,
            is_valid_python=is_valid_python,
            has_imports=has_imports,
            has_endpoint=has_endpoint,
            has_error_handling=has_error_handling,
            has_type_hints=has_type_hints,
            syntax_errors=syntax_errors,
            missing_elements=missing_elements
        )
    
    def format_evaluation_result(self, result: EvaluationResult) -> str:
        """
        Formats the evaluation result into a readable string.
        """
        output = []
        output.append("FastAPI Evaluator Results:")
        output.append(f"  Overall Score: {result.score * 100:.1f}/100")
        output.append(f"  Valid Python: {'✓' if result.is_valid_python else '✗'}")
        output.append(f"  Has FastAPI Imports: {'✓' if result.has_imports else '✗'}")
        output.append(f"  Has Endpoints: {'✓' if result.has_endpoint else '✗'}")
        output.append(f"  Has Error Handling: {'✓' if result.has_error_handling else '✗'}")
        output.append(f"  Has Type Hints: {'✓' if result.has_type_hints else '✗'}")
        
        if result.syntax_errors:
            output.append("  Syntax Errors:")
            for error in result.syntax_errors:
                output.append(f"    • {error}")
                
        if result.missing_elements:
            output.append("  Missing Elements:")
            for element in result.missing_elements:
                output.append(f"    • {element}")
        
        return "\n".join(output)